version: '3.8'

services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.1
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      weaviate:
        condition: service_healthy
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    restart: unless-stopped
    volumes:
      - ./docs:/app/docs
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  weaviate_data:

networks:
  default:
    driver: bridge